name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  run: 
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
      - name: set ssh-agent
        uses: webfactory/ssh-agent@v0.5.2
        with: 
          ssh-private-key: ${{ secrets.KEY }}
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/bots/currency_bot
            echo "hello"
            git pull

